from pathlib import Path

path = Path('agents/forecast.py')
text = path.read_text()
old_def = '''def production(name, fertilize, day, end_day, tile=None):\n    \"\"\"Remaining output, including held yield, without inventing replants.\"\"\"\n'''
new_def = '''def _simulate_production(name, fertilize, day, end_day, tile=None):\n    \"\"\"Uncached interpreter-backed production simulation.\"\"\"\n'''
if old_def not in text:
    raise SystemExit('production function anchor not found')
text = text.replace(old_def, new_def, 1)
anchor = '''    return result\n\n\nclass MarketForecast:\n'''
if anchor not in text:
    raise SystemExit('production return anchor not found')
wrapper = '''    return result\n\n\ndef _production_snapshot(result):\n    \"\"\"Compact immutable representation safe to retain in an LRU cache.\"\"\"\n    return (\n        tuple((day, tuple(sorted(units.items()))) for day, units in sorted(result.sales.items())),\n        tuple((day, tuple(sorted(units.items()))) for day, units in sorted(result.inputs.items())),\n        tuple((day, tuple(visits)) for day, visits in sorted(result.visits.items())),\n    )\n\n\ndef _restore_production(snapshot):\n    result = Production()\n    sales, inputs, visits = snapshot\n    for day, units in sales:\n        result.sales[day].update(dict(units))\n    for day, units in inputs:\n        result.inputs[day].update(dict(units))\n    for day, entries in visits:\n        result.visits[day].extend(entries)\n    return result\n\n\ndef _fertilize_cache_key(fertilize):\n    # Dynamic plans are frozen dataclasses; legacy callers may still pass lists\n    # or sets. Normalize only mutable containers, preserving plan semantics.\n    if isinstance(fertilize, list):\n        return tuple(_fertilize_cache_key(value) for value in fertilize)\n    if isinstance(fertilize, set):\n        return tuple(sorted(_fertilize_cache_key(value) for value in fertilize))\n    if isinstance(fertilize, tuple):\n        return tuple(_fertilize_cache_key(value) for value in fertilize)\n    return fertilize\n\n\ndef _tile_cache_key(tile):\n    if tile is None:\n        return None\n    # Kaggriculture producer tiles are flat dictionaries of primitive values.\n    # Keeping every field in the key is intentionally conservative: a new\n    # engine field automatically invalidates sharing instead of risking a stale\n    # forecast based on an incomplete hand-picked state signature.\n    return tuple(sorted(tile.items()))\n\n\n@lru_cache(maxsize=4096)\ndef _cached_production_snapshot(name, fertilize, day, end_day, tile_key):\n    tile = None if tile_key is None else dict(tile_key)\n    return _production_snapshot(\n        _simulate_production(name, fertilize, day, end_day, tile)\n    )\n\n\ndef production(name, fertilize, day, end_day, tile=None):\n    \"\"\"Remaining output with exact state-keyed interpreter forecast caching.\"\"\"\n    snapshot = _cached_production_snapshot(\n        name, _fertilize_cache_key(fertilize), int(day), int(end_day),\n        _tile_cache_key(tile),\n    )\n    # Return a fresh object to preserve the public function's old ownership\n    # semantics even though the expensive simulation result is shared.\n    return _restore_production(snapshot)\n\n\nclass MarketForecast:\n'''
text = text.replace(anchor, wrapper, 1)
path.write_text(text)
