"""Bounded finite-horizon production paths for planner target valuation.

A path commits only its first producer cycle. Later steps are forecast
continuations used to compare different occupancy windows on equal footing;
they are repriced when their real turnover day arrives.

Animals are terminal commitments: once an animal is placed there is no legal
DIG replacement while it is alive, so animal paths always run to the planner
horizon and never contain a successor.
"""
from __future__ import annotations

from dataclasses import dataclass

from agents.fertilizer import FertilizerPlan
from agents.forecast import Production, production
from agents.horizon import first_yield_age
from agents.products import ANIMALS, ANIMAL_COST, CROPS, SEED_COST
from agents.schedules import CROP_FERTILIZE_DAYS, CROP_LAST_AGE


# Continuation selection deliberately stays tiny. The old planner evaluated up
# to dozens of fertilizer/rotation variants per tile; an exhaustive tree of
# mixed crop paths would grow exponentially and violate the 0.75s action limit.
# Keep two economically distinct successor names, then reprice those against
# the supply already generated by the partial path.
CONTINUATION_WIDTH = 2


@dataclass(frozen=True)
class CycleCandidate:
    choice: tuple
    output: Production
    capital_cost: float
    start_day: int
    next_start: int | None


def _merge(*flows):
    result = Production()
    for flow in flows:
        result.add(flow, include_visits=False)
    return result


def _crop_fertilizer_variants(name, start_day, end_day):
    """Every legal fertilizer subset for one physical crop cycle only."""
    ages = tuple(
        age for age in sorted(CROP_FERTILIZE_DAYS[name])
        if start_day + age <= end_day
    )
    for mask in range(1 << len(ages)):
        selected = tuple(age for bit, age in enumerate(ages) if mask & (1 << bit))
        yield FertilizerPlan((selected,))


def cycle_candidates(start_day, end_day, names=None):
    """Return bounded one-cycle alternatives beginning on ``start_day``.

    Crop output stops naturally at its lifecycle end in ``production``. Animal
    output runs through ``end_day`` and therefore has no continuation.
    """
    allowed = set((*CROPS, *ANIMALS) if names is None else names)
    rows = []
    for name in sorted(allowed):
        if name not in CROPS and name not in ANIMALS:
            continue
        if start_day + first_yield_age(name) > end_day:
            continue
        if name in ANIMALS:
            rows.append(CycleCandidate(
                (name, False), production(name, False, start_day, end_day),
                ANIMAL_COST[name], start_day, None,
            ))
            continue
        for fertilize in _crop_fertilizer_variants(name, start_day, end_day):
            rows.append(CycleCandidate(
                (name, fertilize),
                production(name, fertilize.cycle(), start_day, end_day),
                SEED_COST[name], start_day, start_day + CROP_LAST_AGE[name],
            ))
    return rows


def _profit(market, baseline, candidate, baseline_values=None):
    return (
        market.marginal_value(
            baseline, candidate.output,
            {} if baseline_values is None else baseline_values,
        )
        - candidate.capital_cost
    )


def _continuation_shortlist(market, baseline, start_day, end_day, width):
    """Keep the best one-cycle fertilizer variant for the best few names.

    Ranking is relative to the rest of the farm only. During actual path
    construction the shortlist is repriced against the partial path too, so a
    first crop's own supply can still make the second-best product preferable.
    """
    values = {}
    best_by_name = {}
    for candidate in cycle_candidates(start_day, end_day):
        score = _profit(market, baseline, candidate, values)
        name = candidate.choice[0]
        previous = best_by_name.get(name)
        if previous is None or (score, candidate.choice) > (previous[0], previous[1].choice):
            best_by_name[name] = (score, candidate)
    ranked = sorted(
        (row for row in best_by_name.values() if row[0] > 0),
        key=lambda row: (-row[0], row[1].choice),
    )
    return tuple(candidate for _score, candidate in ranked[:width])


def production_path_candidates(
    market, baseline, start_day, end_day, *, first_names=None,
    continuation_width=CONTINUATION_WIDTH,
):
    """Build one bounded greedy continuation path for every first-cycle choice.

    The first cycle is the only commitment returned to the operational planner.
    Each later cycle is a forecast assumption. At every turnover we shortlist
    a couple of strong successor *names* against the shared farm baseline, then
    reprice those choices against baseline + this path's accumulated supply.

    Return rows compatible with ``planner.evaluate_targets`` plus a fourth path
    field: ``(choice, output, capital_cost, ((start_day, choice), ...))``.
    """
    first = cycle_candidates(start_day, end_day, first_names)
    shortlist_cache = {}
    rows = []

    def shortlist(when):
        if when not in shortlist_cache:
            shortlist_cache[when] = _continuation_shortlist(
                market, baseline, when, end_day, continuation_width
            )
        return shortlist_cache[when]

    for initial in first:
        path_output = _merge(initial.output)
        capital_cost = initial.capital_cost
        steps = [(initial.start_day, initial.choice)]
        next_start = initial.next_start

        # Animal paths terminate immediately by construction. Crop paths may
        # reuse the tile on the same day as their final HARVEST/DIG.
        while next_start is not None and next_start <= end_day:
            alternatives = shortlist(next_start)
            if not alternatives:
                break
            path_base = _merge(baseline, path_output)
            values = {}
            scored = [
                (_profit(market, path_base, candidate, values), candidate)
                for candidate in alternatives
            ]
            score, chosen = max(scored, key=lambda row: (row[0], row[1].choice))
            if score <= 0:
                break
            path_output.add(chosen.output, include_visits=False)
            capital_cost += chosen.capital_cost
            steps.append((chosen.start_day, chosen.choice))
            next_start = chosen.next_start

        rows.append((initial.choice, path_output, capital_cost, tuple(steps)))
    return rows
