"""Create today's v2 TileJobs from locked experiment schedules.

Legacy farm_tasks is retained only for setup/transition mechanics and target
materialization.  Once a producer is live and its target still matches, its
maintenance actions come from the ScheduleBook variant locked for that
lifecycle.
"""

from __future__ import annotations

from collections import Counter

from kaggle_environments.envs.kaggriculture import kaggriculture as official_game

from agents.farm_tasks import build_tasks
from agents.v2_lifecycle import ANIMALS, CROPS, ScheduleBook
from agents.v2_model import TileJob, _safe_split, jobs_from_tasks
from experiments.crop_schedules import CASES

ONGOING_CROPS = {"TOMATO", "STRAWBERRY"}


def _crop_job(obs, position, tile, target, schedule, legacy_job):
    day = obs["day"]
    crop = tile["crop"]
    age = day - tile["planted_day"]
    actions = []
    needs = Counter()
    produces = Counter()

    # Ongoing crops free held capacity before the day's other maintenance;
    # one-time crops take their final WATER before HARVEST.
    if crop in ONGOING_CROPS and age in schedule.harvest:
        actions.append(("HARVEST",))
        produces[crop] += int(tile.get("yield_units", 0))

    if age in schedule.fertilize:
        actions.append(("FERTILIZE",))
        needs["FERTILIZER"] += 1

    if age in schedule.water and not tile.get("watered_today"):
        actions.append(("WATER",))

    if crop not in ONGOING_CROPS and age in schedule.harvest:
        actions.append(("HARVEST",))
        # The experiment schedule guarantees max yield here. Use the verified
        # amount for same-day inventory planning even when the observation is
        # immediately before the final WATER action.
        expected = CASES[(crop, bool(target[1]))]["expected_yields"][-1]
        produces[crop] += max(int(tile.get("yield_units", 0)), int(expected))

        # Continuous rotation: preserve the transition suffix generated by
        # farm_tasks (PLANT -> WATER) but never import generic DIG.
        if legacy_job:
            names = [action[0] for action in legacy_job.actions]
            if "HARVEST" in names:
                cut = names.index("HARVEST") + 1
                for action in legacy_job.actions[cut:]:
                    if action[0] != "DIG":
                        actions.append(tuple(action))
                needs.update(legacy_job.needs)

    if not actions:
        return None
    action_tuple = tuple(actions)
    return TileJob(
        position,
        action_tuple,
        +needs,
        +produces,
        _safe_split(action_tuple),
    )


def _animal_job(obs, position, tile, schedule):
    day = obs["day"]
    animal = tile["animal"]
    age = day - tile["placed_day"]
    actions = []
    needs = Counter()
    produces = Counter()

    if age in schedule.harvest:
        actions.append(("HARVEST",))
        product = official_game.ANIMALS[animal]["product"]
        produces[product] += int(tile.get("yield_units", 0))

    if age in schedule.collect:
        actions.append(("COLLECT_FERTILIZER",))
        produces["FERTILIZER"] += int(bool(tile.get("fertilizer_available")))

    if age in schedule.feed and not tile.get("fed_today"):
        actions.append(("FEED",))
        needs["WHEAT"] += 1

    if age in schedule.care and not tile.get("cared_today"):
        actions.append(("CARE",))

    if not actions:
        return None
    action_tuple = tuple(actions)
    return TileJob(
        position,
        action_tuple,
        +needs,
        +produces,
        _safe_split(action_tuple),
    )


def build_v2_jobs(
    obs,
    targets,
    schedule_book: ScheduleBook,
    assume_crop_seeds=False,
    assume_animal_inputs=False,
):
    """Return every required job today with no priority classification."""
    legacy_tasks = build_tasks(
        obs,
        targets,
        assume_crop_seeds=assume_crop_seeds,
        assume_animal_inputs=assume_animal_inputs,
        prioritize_fertilizer_drop=False,
    )
    legacy_jobs = jobs_from_tasks(legacy_tasks)
    by_position = {job.position: job for job in legacy_jobs}

    schedule_book.sync(obs, targets)
    farm = obs["farms"][obs["player"]]
    replaced = set()
    result = []

    for position, lifecycle in sorted(schedule_book.tiles.items()):
        x, y = position
        tile = farm["tiles"][y][x]
        target = targets.get(position)
        producer = tile.get("animal") or (
            tile.get("crop") if tile.get("kind") == "PLANT" else None
        )
        # A target change is a transition job; retain legacy transition logic.
        if not target or target[0] != producer:
            continue

        if producer in CROPS:
            job = _crop_job(
                obs, position, tile, target, lifecycle.schedule, by_position.get(position)
            )
        elif producer in ANIMALS:
            job = _animal_job(obs, position, tile, lifecycle.schedule)
        else:
            job = None
        replaced.add(position)
        if job:
            result.append(job)

    result.extend(job for job in legacy_jobs if job.position not in replaced)
    return result
